require("jquery")
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("bootstrap/dist/js/bootstrap")

require("./top/slide")
require("./tournament/image_list")
require("./preview/image_preview")
require("./tournament/held_list")
